import type { Metadata } from "next";
import { Urbanist } from "next/font/google";
import "./globals.css";
import { NotesProvider } from "./provider/notes-provider";

const urbanist = Urbanist({
  subsets: ["latin"],
  weight: ["400", "700"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${urbanist.className} antialiased`}
      >

        <NotesProvider>

          {children}
        </NotesProvider>
      </body>
    </html>
  );
}
